---
# vars file for pbis

# Domain settings / Account
domain_fqdn: harlandclarke.local
domain_netbios: HARLANDCLARKE
domain_user: USERNAME
domain_pass: PASSWORD

# Config settings
homedir_template: "%H/%U"
login_shell_template: "/bin/bash"
assume_default_domain: "True"
require_membership_of: '"HARLANDCLARKE\\aix_admins" "HARLANDCLARKE\\another-group"'
